Repository TheRedCandyy/MassDiscoverWebsite, pull requests merged in 2023-05, with the labels that each got.

#40 Develop to main
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/LandingText.js
  client/src/components/MetricsBoxes.js
  client/src/components/Navbar.js
  client/src/components/SearchBar.js
  client/src/components/SearchPage.js
  client/src/index.css
  server/.gitignore
  server/credentials.js
  server/db.js
  server/index.js
  server/middleware/rateLimited.js
  server/package-lock.json
  server/package.json
Labels: FE, BE, DB/Other

#41 MD-024:ADD: Added a new POST request to handle saving the subdomains and domain in the database
  .gitignore
  server/index.js
Labels: BE

#44 MD-018:ADD: Implemented Search Page go back CTA
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/GoBackButton.js
  client/src/components/InfoText.js
  client/src/components/SearchPage.js
Labels: FE
