Repository TheRedCandyy/MassDiscoverWebsite, pull requests merged in 2023-03, with the labels that each got.

#26 MD-012:ADD: Added react-icons and navbar to landing page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Navbar.js
Labels: FE

#28 MD-013:ADD: Implemented title, text, search bar
  client/src/App.js
  client/src/components/LandingText.js
  client/src/index.css
  server/package-lock.json
Labels: FE

#31 MD-002:ADD: Connection to the database
  server/db.js
Labels: BE

#32 MD-006:ADD: Moved the db credentials to a constant file
  server/.gitignore
  server/credentials.js
Labels: BE, DB/Other
